### ISSUE TITLE
sanitize: `p_` in constructor names

### ISSUE THREAD

**Issue by MelanX** [ModdingX/SourceTransform#1]
## Tested with
**SugarCane**: 2022.01.23-1.18.1

## Problem
As you can see in the image below, some parameter names in this constructor have `p_` in front of the normal name. This shouldn't be the case since there is no local variable with the same name.
![image](https://user-images.githubusercontent.com/26039509/155890998-328704bb-1ea1-42a0-b08c-c89ddc0ce255.png)

**Comment by noeppi-noeppi** [comment]
The forge patch [here](https://github.com/MinecraftForge/MinecraftForge/blob/1.18.x/patches/minecraft/net/minecraft/world/level/storage/loot/LootPool.java.patch#L15-L17) changes the constructor descriptor so SourceTransform fails to locate the constructor referenced in parchment data and applies default sanitizing. Works as intended.
